name: PR VirusTotal Check

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '*.installer.yaml'

jobs:
  virus-check:
    runs-on: windows-latest
    name: Check Installer URLs for Malware

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Find Manifest Files
        id: manifest-files
        uses: actions/github-script@v6
        with:
          script: |
            const glob = require('@actions/glob');
            const globber = await glob.create('*.installer.yaml');
            const files = await globber.glob();
            core.setOutput('files', files.join('\n'));

      - name: Run VirusTotal Check on Manifest Files
        run: |
          $files = "${{ steps.manifest-files.outputs.files }}".Split("`n")
          foreach ($file in $files) {
            if (-not [string]::IsNullOrWhiteSpace($file)) {
              Write-Host "Checking file: $file"
              .\scripts\validation-malware.ps1 -ApiKey ${{ secrets.VIRUSTOTAL_API_KEY }} -ManifestPath $file
            }
          }
        shell: pwsh
