name: Winget PR Test

on:
  pull_request:
    paths:
      - 'manifests/**'

jobs:
  test-winget-install:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetches all history for all branches and tags

    - name: Run winget test script
      shell: pwsh
      run: |
        git fetch origin master:master
        $modifiedManifests = git diff --name-only master...HEAD -- 'manifests/**/*.yaml'
        foreach ($manifest in $modifiedManifests) {
            .\scripts\validation.ps1 -ManifestPath $manifest
        }
